---
title: "Cleaning data"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# Loading packages

```{r}

library("tidyverse")

source(file = "R/99_proj_func.R")
```

# Loading data files

```{r}

blood <- read_csv(file = "data/blood_load.csv")

tonsil <- read_csv(file = "data/tonsil_load.csv")

thymus <- read_csv(file = "data/thymus_load.csv")
```

# Cleaning each data set

```{r}

selected_measures <- c("CVQb", "MedQb", "count", "PEpos")

blood_clean <- blood |> 
  pivot_selected_variables(ID_col = "CD",
                           variables = selected_measures,
                           tissue = "blood")
                            

tonsil_clean <- tonsil |> 
  pivot_selected_variables(ID_col = "CD",
                           variables = selected_measures,
                           tissue = "tonsil")

thymus_clean <- thymus |> 
  pivot_selected_variables(ID_col = "CD",
                           variables = selected_measures,
                           tissue = "thymus")

# level_3 <- c("Tgd", "TCD8", "TCD4", "Bnaive", "BnatEff", "BIgM", "BswMem","Bdn", "B27high", "BnaiveTo", "CC", "CB", "UnswtMem", "SwtMem", "PC")

# This will be used later, so just leave it here.
  #mutate(hierarchy_level = case_when(cell_type == "Lymphs" ~ 1,
                                     #cell_type %in% c("T", "B") ~ 2,
                                     #cell_type %in% level_3 ~ 3,
                                     #.default = 4),
         #.after = cell_type)

  #mutate(linage = case_when(str_starts(cell_type, "TCD4") ~ "CD4 T cells",
                            #str_starts(cell_type, "TCD8") ~ "CD8 T cells",
                            #str_starts(cell_type, "T") ~ "T cells",
                            #str_starts(cell_type, "D") ~ "T cells",
                            #.default = "B cells"),
         #.before = cell_type)
```

# Merge the three cleaned data sets

```{r}

level_3 <- c("Tgd", "TCD8", "TCD4", "Bnaive", "BnatEff", "BIgM", "BswMem","Bdn", "B27high", "BnaiveTo", "CC", "CB", "UnswtMem", "SwtMem", "PC")

data_merged <- bind_rows(blood_clean,
                         tonsil_clean,
                         thymus_clean)

data_clean <- data_merged |>
  filter(CD != "FMO") |>
  mutate(hierarchy_level = case_when(cell_type == "Lymphs" ~ 1,
                                     cell_type %in% c("T", "B") ~ 2,
                                     cell_type %in% level_3 ~ 3,
                                     .default = 4),
         .after = cell_type) |>
  mutate(linage = case_when(str_starts(cell_type, "TCD4") ~ "CD4 T cells",
                            str_starts(cell_type, "TCD8") ~ "CD8 T cells",
                            str_starts(cell_type, "T") ~ "T cells",
                            str_starts(cell_type, "D") ~ "T cells",
                            .default = "B cells"),
         .before = cell_type)

```

# Preparing data set for PCA

```{r}


PCA_nested <- data |>
  pivot_wider(id_cols = c("tissue", "cell_type"),
              names_from = "CD",
              values_from = c("MedQb", "PEpos"),
              values_fn = list)

max_len <- PCA_nested |>
  select(starts_with(c("MedQb", "PEpos"))) |> 
  map(lengths) |>
  unlist() |>
  max()

PCA_clean <- PCA_nested |>
  mutate(across(
    starts_with(c("MedQb","PEpos")),
    ~ map(.x, ~ c(.x, rep(NA, max_len - length(.x)))))) |>
  unnest() |>
  filter(!if_all(-c(tissue, cell_type), is.na))
  
```

# Writing data files

```{r}

write_csv(x = data_clean,
          file = "data/data_clean.csv")

write_csv(x = PCA_clean,
          file = "data/PCA_clean.csv")
```
