---
title: "Adding new variables"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# Loading packages

```{r}

library("tidyverse")
library("broom")
library("ggrepel")

source(file = "R/99_proj_func.R")
```

# Loading data files

```{r}

data_clean <- read_csv(file = "data/data_clean.csv")
```

# CD4 vs CD8

```{r}

CD4_vs_CD8 <- data_clean |>
  filter(lineage %in% c("CD4 T cells", "CD8 T cells"),
         cell_type != "CD4ISP",
         cell_type != "TCD8RAdim",
         hierarchy_level == 4) |>
  mutate(pair = case_when(str_ends(cell_type, "naive") ~ "naive",
                          str_ends(cell_type, "CM") ~ "CM",
                          str_ends(cell_type, "EM") ~ "EM",
                          str_detect(cell_type, "TEMRA") ~ "TEMRA",
                          str_detect(cell_type, "SP1ap") ~ "SP1ap",
                          str_detect(cell_type, "SP1am") ~ "SP1am")) |>
  select(-c("CVQb", "count", "PEpos")) 

columns <- c("tissue", 
             "CD", 
             "pair", 
             "p.value", 
             "estimate", 
             "conf.low", 
             "conf.high")

CD4_vs_CD8_sig  <- CD4_vs_CD8 |>
  group_by(tissue, CD, pair) |>
  nest() |>
  mutate(model_object = map(.x = data,
                   .f = ~lm(formula = MedQb ~ cell_type,
                            data = .x))) |>
  mutate(model_object_tidy = map(.x = model_object,
                                 .f = ~tidy(.x, 
                                           conf.int = TRUE,
                                           conf.level = 0.95))) |>
  unnest(model_object_tidy) |>
  filter(str_starts(term, "cell_type")) |>
  select(columns) |>
  ungroup()|>
  mutate(is_significant = case_when(p.value < 0.05 ~ "yes",
                                    p.value >= 0.05 ~ "no"))
  

CD4_vs_CD8_aug <- CD4_vs_CD8 |>
  left_join(y = CD4_vs_CD8_sig,
            by = c("tissue", "CD", "pair"),
            relationship = "many-to-one") |>
  group_by(tissue, CD) |>
  mutate(any_significant = case_when(any(is_significant == "yes") ~ "yes",
                                     .default = "no"))

CD4_vs_CD8_aug |>
  filter(is_significant == "yes",
         pair == "CM") |>
  ggplot(aes(x = CD,
             y = MedQb,
             fill = CD)) +
  geom_boxplot() +
  scale_y_log10() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  facet_wrap(~ cell_type, ncol = 2)

```

# T cells maturation

```{r}

data_sub <- data_clean |>
  cell_type_order() |>
  filter(lineage %in% c("CD8 T cells", "T cells"),
         hierarchy_level == 4,)

# Fit linear models

cd_models <- data_sub |>
  group_by(tissue, CD) |>
  nest() |>
  mutate(
    model_object = map(.x = data,
                       .f = ~ lm(MedQb ~ cell_type, data = .x)),
    model_object_tidy = map(.x = model_object,
                             .f = ~ tidy(.x, 
                                         conf.int = TRUE, 
                                         conf.level = 0.95)))

# Clean and select columns

columns <- c("CD", 
             "tissue", 
             "cell_type_compared", 
             "p.value", 
             "estimate", 
             "conf.low", 
             "conf.high")

cd_results <- cd_models |>
  unnest(model_object_tidy) |>
  filter(term != "(Intercept)") |>
  mutate(cell_type_compared = str_remove(term, "cell_type")) |>
  select(columns) |>
  ungroup() |>
  mutate(is_significant = case_when(p.value < 0.05 ~ "yes",
                                    p.value >= 0.05 ~ "no"))

# Create plots

# Keep only significant comparisons
cd_results_sig <- cd_results |> 
  filter(is_significant == "yes")

forest_plot <- cd_results_sig |>
  ggplot(aes(x = estimate, 
             y = fct_reorder(cell_type_compared, 
                             estimate))) +
  geom_point(size = 3, 
             color = "blue") +  # points for estimates
  geom_errorbarh(aes(xmin = conf.low, 
                     xmax = conf.high), 
                 height = 0.2, 
                 color = "blue") +  # CIs
  geom_vline(xintercept = 0, 
             linetype = "dashed") +  # baseline
  facet_wrap(~ CD, 
             scales = "free_y") +  # one y-axis per CD marker
  labs(
    x = "Difference in MedQb vs first cell type",
    y = " ",
    title = "Significant Differences of CD markers by Cell Type",
    caption = "Data from CD Maps"
  ) +
  theme_minimal() 
  
print(forest_plot)


#Other plots
cd_results |>
  ggplot(aes(x = estimate, 
             y = fct_reorder(cell_type_compared, 
                             estimate), 
             color = is_significant)) +
  geom_segment(aes(x = 0, xend = estimate, 
                   y = cell_type_compared, 
                   yend = cell_type_compared), 
               size = 0.5, 
               color = "gray") +
  geom_point(size = 3) +
  facet_wrap(~ CD, scales = "free_y") +
  scale_color_manual(values = c("no"="gray", 
                                "yes"="blue")) +
  labs(title = "Lollipop plot of CD marker differences",
       x = "Difference vs first cell type", 
       y = "Cell Type", 
       color = "Significant") +
  theme_bw()
```

# Maturation of immune cells

```{r}

columns <- c("CD", 
             "tissue",
             "lineage",
             "cell_type",
             "estimate",
             "conf.low", 
             "conf.high",
             "p.value",
             "is_significant",
             "any_significant")

data_aug <- data_clean |>
  cell_type_order() |>
  filter(hierarchy_level %in% c(3, 4),
         !cell_type %in% c("Tgd", "TCD4", "TCD8")) |>
  select(-c("CVQb", "count", "PEpos")) |>
  drop_na(MedQb) |>
  group_by(tissue, CD, lineage) |>
  nest() |>
  mutate(model_object = map(.x = data,
                   .f = ~lm(formula = MedQb ~ cell_type,
                            data = .x))) |>
  mutate(model_object_tidy = map(.x = model_object,
                                 .f = ~tidy(.x, 
                                           conf.int = TRUE,
                                           conf.level = 0.95))) |>
  unnest(model_object_tidy) |>
  mutate(is_significant = case_when(term == "(Intercept)" ~ "reference",
                                    p.value < 0.05 ~ "yes",
                                    p.value >= 0.05 ~ "no"),
          any_significant = case_when(any(is_significant == "yes") ~ "yes",
                                     .default = "no")) |>
  mutate(
    intercept = estimate[term == "(Intercept)"],
    estimate = case_when(
      term == "(Intercept)" ~ estimate,
      term != "(Intercept)" ~ estimate + intercept),
    conf.low = case_when(
      term == "(Intercept)" ~ conf.low,
      term != "(Intercept)" ~ conf.low + intercept),
    conf.high = case_when(
      term == "(Intercept)" ~ conf.high,
      term != "(Intercept)" ~ conf.high + intercept),
    cell_type = case_when(
      term == "(Intercept)" & tissue == "blood" & lineage == "B cells" ~ "Bnaive",
      term == "(Intercept)" & tissue == "tonsil" ~ "BnaiveTo",
      term == "(Intercept)" & lineage == "CD4 T cells" ~ "TCD4naive", 
      term == "(Intercept)" & lineage == "CD8 T cells" ~ "TCD8naive",
      term == "(Intercept)" & tissue == "thymus"  ~ "DN34p",
    .default = str_remove(term, "cell_type"))) |>
  select(columns) |>
  ungroup()

data_aug |>
  filter(lineage == "B cells",
         CD == "CD11a") |>
    cell_type_order() |>
  ggplot(aes(x = cell_type,
             y = estimate,
             color = is_significant,
             shape = tissue)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1))
```
