---
title: "Analysis 1"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# Loading packages

```{r}

library("tidyverse")

source(file = "R/99_proj_func.R")
```

# Loading data files

```{r}

data_clean <- read_csv(file = "data/data_clean.csv")

```

# Plotting the data

```{r}

data_clean |>
  filter(tissue == "blood") |>
  ggplot(aes(x = PEpos,
             y = MedQb,
             color = lineage)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10() 

```

```{r}

data_clean |>
  cell_type_order() |>
  filter(lineage %in% c("CD8 T cells", "T cells"),
         hierarchy_level == 4,
         CD %in% c("CD10","CD1a"))|>
  ggplot(aes(x = cell_type,
             y = MedQb,
             fill = tissue)) +
  geom_boxplot() +
  scale_y_log10() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  facet_wrap(~ CD, ncol = 1)

```

```{r}

data_clean |>
  cell_type_order() |>
  filter(lineage == "B cells",
         hierarchy_level == 3,
         CD %in% c("CD27","CD95"))|>
  ggplot(aes(x = cell_type,
             y = MedQb,
             fill = tissue)) +
  geom_boxplot() +
  scale_y_log10() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  facet_wrap(~ CD, ncol = 1)
```

```{r}

data_clean |>
  cell_type_order() |>
  filter(lineage == "B cells",
         hierarchy_level == 3,
         tissue == "blood") |>
  drop_na(MedQb) |>
  group_by(CD) |>
  mutate(MedQb_grp = median(MedQb)) |>
  ungroup() |>
  ggplot(aes(x = fct_reorder(CD, MedQb_grp),
             y = MedQb,
             fill = log10(MedQb_grp))) +
  geom_boxplot() +
  scale_y_log10(labels = trans_format("log10", 
                                      math_format(10^.x))) +
  scale_fill_gradient2(low = "lightblue", 
                        mid = "orange", 
                        high = "darkred", 
                        midpoint = 3) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1)) +
  labs(x = "CD",
       y = "Flourescence [Median ABC]",
       fill = "log10(Median ABC)",
       title = paste("Fluorescence of", lineage, "in", tissue))

data_clean |>
  asc_CDs_boxplot(lineage = "B cells",
                  hierarchy_level = 4,
                  tissue = "blood",
                  measure = MedQb)
```
