---
title: "Analysis 4"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# Loading packages

```{r}

library("tidyverse")
library("broom")

source(file = "R/99_proj_func.R")
```

# Loading data files

```{r}

data_aug <- read_csv(file = "data/data_aug.csv")
```

# Maturation of immune cells

```{r}

columns <- c("CD", 
             "tissue",
             "lineage",
             "cell_type",
             "estimate",
             "conf.low", 
             "conf.high",
             "p.value",
             "is_significant",
             "any_significant")

data_analysis4 <- data_aug |>
  cell_type_order() |>
  filter(hierarchy_level %in% c(3, 4),
         !cell_type %in% c("Tgd", "TCD4", "TCD8")) |>
  select(-c("CVQb", "count", "PEpos")) |>
  drop_na(MedQb) |>
  group_by(tissue, CD, lineage) |>
  nest() |>
  mutate(model_object = map(.x = data,
                   .f = ~lm(formula = log(MedQb) ~ cell_type,
                            data = .x))) |>
  mutate(model_object_tidy = map(.x = model_object,
                                 .f = ~tidy(.x, 
                                           conf.int = TRUE,
                                           conf.level = 0.95))) |>
  unnest(model_object_tidy) |>
  mutate(is_significant = case_when(term == "(Intercept)" ~ "reference",
                                    p.value < 0.05 ~ "yes",
                                    p.value >= 0.05 ~ "no"),
          any_significant = case_when(any(is_significant == "yes") ~ "yes",
                                     .default = "no")) |>
  mutate(
    intercept = estimate[term == "(Intercept)"],
    estimate = case_when(
      term == "(Intercept)" ~ estimate,
      term != "(Intercept)" ~ estimate + intercept),
    conf.low = case_when(
      term == "(Intercept)" ~ conf.low,
      term != "(Intercept)" ~ conf.low + intercept),
    conf.high = case_when(
      term == "(Intercept)" ~ conf.high,
      term != "(Intercept)" ~ conf.high + intercept),
    cell_type = case_when(
      term == "(Intercept)" & tissue == "blood" & lineage == "B cells" ~ "Bnaive",
      term == "(Intercept)" & tissue == "tonsil" ~ "BnaiveTo",
      term == "(Intercept)" & lineage == "CD4 T cells" ~ "TCD4naive", 
      term == "(Intercept)" & lineage == "CD8 T cells" ~ "TCD8naive",
      term == "(Intercept)" & tissue == "thymus"  ~ "DN34p",
    .default = str_remove(term, "cell_type"))) |>
  select(columns) |>
  ungroup()
```

## B cells

```{r}

data_analysis4 |>
  filter(lineage == "B cells",
         CD == "CD11a") |>
    cell_type_order() |>
  ggplot(aes(x = cell_type,
             y = estimate,
             color = is_significant,
             shape = tissue)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1))
data_analysis4 |>
  filter(lineage == "B cells",
         CD == "CD69") |>
    cell_type_order() |>
  ggplot(aes(x = cell_type,
             y = estimate,
             color = is_significant,
             shape = tissue)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1))
data_analysis4 |>
  filter(lineage == "B cells",
         CD == "CD79b") |>
    cell_type_order() |>
  ggplot(aes(x = cell_type,
             y = estimate,
             color = is_significant,
             shape = tissue)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1))
data_analysis4 |>
  filter(lineage == "B cells",
         CD == "CD80") |>
    cell_type_order() |>
  ggplot(aes(x = cell_type,
             y = estimate,
             color = is_significant,
             shape = tissue)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1))


```

```{r}
cds_interes <- c("CD11a", "CD69", "CD79b", "CD80")

data_analysis4 |>
  filter(lineage == "B cells",
         CD %in% cds_interes) |>
  cell_type_order() |>
  ggplot(aes(x = cell_type,
             y = estimate,
             color = factor(is_significant, levels = c("reference", "yes", "no")),
             shape = tissue)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high),
                width = 0.4) +
  facet_wrap(~ CD, ncol = 2, scales = "free_y") +
  scale_color_manual(
    name = "Significance",
    values = c("reference" = "black",
               "yes" = "#29cf8f",
               "no" = "#fa2840")
  ) +
  scale_shape_discrete(name = "Tissue") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    strip.text = element_text(size = 14, face = "bold"),
    axis.line = element_line(color = "black") # agrega líneas de los ejes
  ) +
  labs(
    title = "Expression of Selected B-cell Markers",
    x = "Cell Type",
    y = "Estimate"
  )


```

```{r}

data_analysis4 |>
  filter(lineage == "CD8 T cells") |>
  distinct(CD) |>
  print(n=113)
```

## T cells

```{r}

data_analysis4 |>
  filter(lineage %in% c("thymocytes", "CD4 T cells"),
         !str_detect(cell_type, "CD8"),
         CD == "CD10") |>
    cell_type_order() |>
  ggplot(aes(x = cell_type,
             y = estimate,
             color = is_significant,
             shape = tissue)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1))

data_analysis4 |>
  filter(lineage %in% c("thymocytes", "CD4 T cells"),
         !str_detect(cell_type, "CD8"),
         CD == "CD25") |>
    cell_type_order() |>
  ggplot(aes(x = cell_type,
             y = estimate,
             color = is_significant,
             shape = tissue)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1))

data_analysis4 |>
  filter(lineage %in% c("thymocytes", "CD4 T cells"),
         !str_detect(cell_type, "CD8"),
         CD == "CD4_MEM-241") |>
    cell_type_order() |>
  ggplot(aes(x = cell_type,
             y = estimate,
             color = is_significant,
             shape = tissue)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1))

data_analysis4 |>
  filter(lineage %in% c("thymocytes", "CD4 T cells"),
         !str_detect(cell_type, "CD8"),
         CD == "CD62L") |>
    cell_type_order() |>
  ggplot(aes(x = cell_type,
             y = estimate,
             color = is_significant,
             shape = tissue)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1))
```

```{r}
cds_interes <- c("CD10", "CD25", "CD4_MEM-241", "CD62L")

data_analysis4 |>
  filter(lineage %in% c("thymocytes", "CD4 T cells"),
         !str_detect(cell_type, "CD8"),
         CD %in% cds_interes) |>
 cell_type_order() |>
  ggplot(aes(x = cell_type,
             y = estimate,
             color = factor(is_significant, levels = c("reference", "yes", "no")),
             shape = tissue)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high),
                width = 0.4) +
  facet_wrap(~ CD, ncol = 2, scales = "free_y") +
  scale_color_manual(
    name = "Significance",
    values = c("reference" = "black",
               "yes" = "#29cf8f",
               "no" = "#fa2840")
  ) +
  scale_shape_discrete(name = "Tissue") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    strip.text = element_text(size = 14, face = "bold"),
    axis.line = element_line(color = "black") # agrega líneas de los ejes
  ) +
 labs(
    title = "Expression of Selected CD4 T Cell and Thymocyte Markers",
    x = "Cell Type",
    y = "Estimate"
  )
```

```{r}

data_analysis4 |>
  filter(lineage %in% c("thymocytes", "CD8 T cells"),
         !str_detect(cell_type, "CD4"),
         CD == "CD27") |>
    cell_type_order() |>
  ggplot(aes(x = cell_type,
             y = estimate,
             color = is_significant,
             shape = tissue)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1))

data_analysis4 |>
  filter(lineage %in% c("thymocytes", "CD8 T cells"),
         !str_detect(cell_type, "CD4"),
         CD == "CD38") |>
    cell_type_order() |>
  ggplot(aes(x = cell_type,
             y = estimate,
             color = is_significant,
             shape = tissue)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1))

data_analysis4 |>
  filter(lineage %in% c("thymocytes", "CD8 T cells"),
         !str_detect(cell_type, "CD4"),
         CD == "CD71") |>
    cell_type_order() |>
  ggplot(aes(x = cell_type,
             y = estimate,
             color = is_significant,
             shape = tissue)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1))

data_analysis4 |>
  filter(lineage %in% c("thymocytes", "CD8 T cells"),
         !str_detect(cell_type, "CD4"),
         CD == "CD95") |>
    cell_type_order() |>
  ggplot(aes(x = cell_type,
             y = estimate,
             color = is_significant,
             shape = tissue)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1))
```

```{r}
cds_interes <- c("CD27", "CD38", "CD71", "CD95")

data_analysis4 |>
  filter(lineage %in% c("thymocytes", "CD8 T cells"),
         !str_detect(cell_type, "CD4"),
         CD %in% cds_interes) |>
 cell_type_order() |>
  ggplot(aes(x = cell_type,
             y = estimate,
             color = factor(is_significant, levels = c("reference", "yes", "no")),
             shape = tissue)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high),
                width = 0.4) +
  facet_wrap(~ CD, ncol = 2, scales = "free_y") +
  scale_color_manual(
    name = "Significance",
    values = c("reference" = "black",
               "yes" = "#29cf8f",
               "no" = "#fa2840")
  ) +
  scale_shape_discrete(name = "Tissue") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    strip.text = element_text(size = 14, face = "bold"),
    axis.line = element_line(color = "black") # agrega líneas de los ejes
  ) +
 labs(
    title = "Expression of Selected CD8 T Cell and Thymocyte Markers",
    x = "Cell Type",
    y = "Estimate"
  )
```
