---
title: "Analysis 5"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# Loading packages

```{r}

library("tidyverse")
library("broom")

source(file = "R/99_proj_func.R")

```

# Loading data files

```{r}

data_aug <- read_csv(file = "data/data_aug.csv")

```

# Differences in CD makers on CD4 and CD8 T cells

```{r}

columns <- c("tissue", 
             "CD",
             "cell_type",
             "pair",
             "estimate", 
             "conf.low", 
             "conf.high",
             "p.value",
             "is_significant",
             "any_significant")

CD4_vs_CD8  <- data_aug |>
  filter(lineage %in% c("CD4 T cells", "CD8 T cells"),
         cell_type != "CD4ISP",
         cell_type != "TCD8RAdim",
         hierarchy_level == 4) |>
  mutate(pair = case_when(str_ends(cell_type, "naive") ~ "naive",
                          str_ends(cell_type, "CM") ~ "CM",
                          str_ends(cell_type, "EM") ~ "EM",
                          str_detect(cell_type, "TEMRA") ~ "TEMRA",
                          str_detect(cell_type, "SP1ap") ~ "SP1ap",
                          str_detect(cell_type, "SP1am") ~ "SP1am")) |>
  group_by(tissue, CD, pair) |>
  nest() |>
  mutate(model_object = map(.x = data,
                   .f = ~lm(formula = log(MedQb) ~ cell_type,
                            data = .x))) |>
  mutate(model_object_tidy = map(.x = model_object,
                                 .f = ~tidy(.x, 
                                           conf.int = TRUE,
                                           conf.level = 0.95))) |>
  unnest(model_object_tidy) |>
  mutate(is_significant = case_when(term == "(Intercept)" ~ "reference",
                                    p.value < 0.05 ~ "yes",
                                    p.value >= 0.05 ~ "no"),
          any_significant = case_when(any(is_significant == "yes") ~ "yes",
                                     .default = "no")) |>
  mutate(
    intercept = estimate[term == "(Intercept)"],
    estimate = case_when(
      term == "(Intercept)" ~ estimate,
      term != "(Intercept)" ~ estimate + intercept),
    conf.low = case_when(
      term == "(Intercept)" ~ conf.low,
      term != "(Intercept)" ~ conf.low + intercept),
    conf.high = case_when(
      term == "(Intercept)" ~ conf.high,
      term != "(Intercept)" ~ conf.high + intercept),
    cell_type = case_when(
      term == "(Intercept)" & pair == "naive" ~ "TCD4naive",
      term == "(Intercept)" & pair == "CM" ~ "TCD4CM",
      term == "(Intercept)" & pair == "EM" ~ "TCD4EM", 
      term == "(Intercept)" & pair == "TEMRA" ~ "TCD4TEMRA",
      .default = str_remove(term, "cell_type"))) |>
  select(columns) |>
  ungroup() |>
  filter(any_significant == "yes") |>
  mutate(lineage = case_when(str_detect(cell_type, "CD4") ~ "CD4 T cells",
                             .default = "CD8 T cells"),
         .before = cell_type)

```

```{r}

p1 <- CD4_vs_CD8 |>
  filter(pair == "naive") |>
  ggplot(aes(x = CD,
             y = estimate,
             color = lineage)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high),
                width = 0.4) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1)) +
  theme(legend.position = "none") +
  scale_color_manual(values = c("CD4 T cells" = "navy",
                                "CD8 T cells" = "hotpink")) +
  labs(title = "CD4naive vs CD8naive",
       x = "Significant CDs",
       y = "Estimate of log(MedQb)",
       color = "Lineage")

p2 <- CD4_vs_CD8 |>
  filter(pair == "CM") |>
  ggplot(aes(x = CD,
             y = estimate,
             color = lineage)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high),
                width = 0.4) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1)) +
  theme(legend.position = "none") +
  scale_color_manual(values = c("CD4 T cells" = "navy",
                                "CD8 T cells" = "hotpink")) +
  labs(title = "CD4CM vs CD8CM",
       x = "Significant CDs",
       y = "Estimate of log(MedQb)",
       color = "Lineage")

p3 <- CD4_vs_CD8 |>
  filter(pair == "EM") |>
  ggplot(aes(x = CD,
             y = estimate,
             color = lineage)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high),
                width = 0.4) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1)) +
  theme(legend.position = "none") +
  scale_color_manual(values = c("CD4 T cells" = "navy",
                                "CD8 T cells" = "hotpink")) +
  labs(title = "CD4EM vs CD8EM",
       x = "Significant CDs",
       y = "Estimate of log(MedQb)",
       color = "Lineage")

p4 <- CD4_vs_CD8 |>
  filter(pair == "TEMRA") |>
  ggplot(aes(x = CD,
             y = estimate,
             color = lineage)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = conf.low,
                    ymax = conf.high),
                width = 0.4) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, 
                                   vjust = 0.5, 
                                   hjust = 1)) +
  theme(legend.position = "bottom") +
  scale_color_manual(values = c("CD4 T cells" = "navy",
                                "CD8 T cells" = "hotpink")) +
  labs(title = "CD4TEMRA vs CD8TEMRA",
       x = "Significant CDs",
       y = "Estimate of log(MedQb)",
       color = "Lineage")

(p1 + p2) / (p3 + p4)
```

```{r}

p1 <- CD4_vs_CD8 |>
  plot_CD4vsCD8(pair = "naive",
                legend_position = "none")

p2 <- CD4_vs_CD8 |>
  plot_CD4vsCD8(pair = "CM",
                legend_position = "none")

p3 <- CD4_vs_CD8 |>
  plot_CD4vsCD8(pair = "EM",
                legend_position = "none")

p4 <- CD4_vs_CD8 |>
  plot_CD4vsCD8(pair = "TEMRA",
                legend_position = "none")

(p1 + p2) / (p3 + p4)
```
